name: Deploy GitOps Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Log in to Argo CD
      run: |
        kubectl port-forward svc/argocd-server -n argocd 8080:443 & 
        sleep 5
        argocd login localhost:8080 --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
        argocd account generate-token --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }} --name demo-token

    - name: Build Docker image
      run: |
        docker build -t lssalas/hola-mundo-gitops:latest .

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push lssalas/hola-mundo-gitops:latest
