name: Deploy GitOps Demo

on:
  push:
    branches:
      - main          # Se activa cuando hay un cambio en la rama "main"

jobs:
  build:
    runs-on: ubuntu-latest  # El pipeline se ejecuta en un runner Ubuntu

    steps:
    - name: Checkout code   # Descarga el c칩digo del repositorio
      uses: actions/checkout@v3

    - name: Set up Docker Buildx # Configura Docker para compilaci칩n avanzada
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub # Inicia sesi칩n en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Usuario de Docker Hub (almacenado como secreto)
        password: ${{ secrets.DOCKER_PASSWORD }} # Contrase침a de Docker Hub (almacenada como secreto)

    - name: Build and push Docker image # Construye y sube la imagen Docker
      uses: docker/build-push-action@v5
      with:
        context: .                     # Usa el directorio actual como contexto
        file: ./Dockerfile             # Especifica el archivo Dockerfile
        push: true                     # Publica la imagen en Docker Hub
        tags: lssalas/gitops-demo:latest # Etiqueta de la imagen Docker
